language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t davidalba/docker-react .

script:
  - docker run -e CI=true davidalba/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  environment: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-348179825777"
  bucket_path: "docker"
  access_key_id:
    secure: $AWS_ACCESS_KEY 
  secret_access_key:
    secure: $AWS_SECRET_KEY
  on:
    branch: master



